backend/store/api/urls.py
from django.urls import path
from .views import ProductAPIVew, CollectionAPIVew, CategoryProductAPIVew, ClothingCategoriesAPIVew, \
    ClientCategoryAPIVew, StockAPIVew, ProductDetailAPIVew, CreateClientCategoryAPIVew, CreateCollectionAPIVew, \
    CreateClothingCategoriesAPIVew, CreateProductAPIVew, CreateStockAPIVew, CreateCategoryProductAPIVew


urlpatterns =[
    path('products/', ProductAPIVew.as_view()),
    path('collection/', CollectionAPIVew.as_view()),
    path('category_product/', CategoryProductAPIVew.as_view()),
    path('clothing_categories/', ClothingCategoriesAPIVew.as_view()),
    path('client_category/', ClientCategoryAPIVew.as_view()),
    path('stock/', StockAPIVew.as_view()),
    path('products/<int:pk>/', ProductDetailAPIVew.as_view()),
    #API для добавления
    path('add_client_category', CreateClientCategoryAPIVew.as_view()),
    path('add_collection', CreateCollectionAPIVew.as_view()),
    path('add_clothing_categories', CreateClothingCategoriesAPIVew.as_view()),
    path('add_product', CreateProductAPIVew.as_view()),
    path('add_stock', CreateStockAPIVew.as_view()),
    path('add_category_product', CreateCategoryProductAPIVew.as_view()),
]

backend/store/orders/urls.py
from django.urls import path
from .views import order_create, OrderList, OrderUpdate, OrderDetail


app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('order_list/', OrderList.as_view(), name='order_list'),
    path('order_update/<int:pk>/', OrderUpdate.as_view(), name='order_update'),
    path('order_detail/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
]

backend/store/store/urls.py
from django.contrib import admin
from django.urls import path, include
#импорты для настройки картинки
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('sign/', include('sign.urls')),
    path('profile/', include('protect.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
] #+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # без этой настройки не будет отображения картинки

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/store/orders/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
from shop.models import CustomUser


class Order(models.Model):
    DELIVERY = [
        ('post_office', 'Почтой России'),
        ('transport_company', 'Транспортной компанией'),
        ('pickup', 'Самовывоз'),
    ]

    CHOICES_PAY = [
        ('credit_card', 'Оплата картой онлайн'),
    ]

    # authorUser = models.ForeignKey(User, verbose_name='клиент', on_delete=models.CASCADE, null=True)
    authorUser = models.ForeignKey(CustomUser, verbose_name='клиент', on_delete=models.CASCADE, null=True)
    name = models.CharField(verbose_name='ФИО', max_length=250)
    country = models.CharField(verbose_name='страна', max_length=100, null=True)
    # last_name = models.CharField(max_length=50)
    email = models.EmailField(verbose_name='эл.почта')
    address = models.CharField(verbose_name='адрес', max_length=350)
    postal_code = models.CharField(verbose_name='индекс', max_length=20)
    city = models.CharField(verbose_name='город', max_length=100)
    phone = models.BigIntegerField(verbose_name='номер телефона', null=True) #TODO переделать на PhoneNumberField
    delivery = models.CharField(verbose_name='способ доставки', max_length=100, choices=DELIVERY, default='pickup', null=True)
    type_pay = models.CharField(verbose_name='способ оплаты', max_length=100, choices=CHOICES_PAY, default='credit_card', null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'Заказ № {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_absolute_url(self):
        return f'/orders/order_list/'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    user = models.CharField(max_length=250, null=True)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    color = models.CharField(max_length=250, null=True)
    size = models.CharField(max_length=250, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

backend/store/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = [
            'country',
            'city',
            'postal_code',
            'address',
            'name',
            'email',
            'phone',
            'delivery',
            'type_pay'
        ]

        widgets = {
            'country': forms.TextInput(
                attrs={
                    "class": "form-control",
                    "style": "border-left: 0; border-top: 0; border-right: 0; padding-left: 0; border-radius: 0",
                    "placeholder": 'Страна',
                }
            ),

            'city': forms.TextInput(
                attrs={
                    "class": "form-control",
                    "style": "border-left: 0; border-top: 0; border-right: 0; padding-left: 0; border-radius: 0",
                    "placeholder": 'Город',
                }
            ),

            'postal_code': forms.TextInput(
                attrs={
                    "class": "form-control",
                    "style": "border-left: 0; border-top: 0; border-right: 0; padding-left: 0; border-radius: 0",
                    "placeholder": 'Индекс',
                }
            ),

            'address': forms.TextInput(
                attrs={
                    "class": "form-control",
                    "style": "border-left: 0; border-top: 0; border-right: 0; padding-left: 0; border-radius: 0",
                    "placeholder": 'Адресс',
                }
            ),

            'name': forms.TextInput(
                attrs={
                    "class": "form-control",
                    "style": "border-left: 0; border-top: 0; border-right: 0; padding-left: 0; border-radius: 0",
                    "placeholder": 'ФИО',
                }
            ),

            'email': forms.EmailInput(
                attrs={
                    "class": "form-control",
                    "style": "border-left: 0; border-top: 0; border-right: 0; padding-left: 0; border-radius: 0",
                    "placeholder": 'Email',
                }
            ),

            'phone': forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "style": "border-left: 0; border-top: 0; border-right: 0; padding-left: 0; border-radius: 0",
                    "placeholder": 'Телефон',
                }
            ),

            'delivery': forms.RadioSelect,

            'type_pay': forms.RadioSelect

        }

        # country = forms.CharField(
        #     label='Страна',
        #     widget=forms.TextInput(
        #         attrs={
        #             "class": "form-control",
        #             "style": "border-left: 0; border-top: 0; border-right: 0; padding-left: 0; border-radius: 0",
        #             "placeholder": 'Страна',
        #         }
        #     )
        # )

        # CHOICES_PAY = [
        #     ('Оплата картой онилайн', 'Оплата картой онилайн'),
        # ]
        #
        # type_pay = forms.MultipleChoiceField(
        #     required=False,
        #     # widget=forms.CheckboxSelectMultiple,
        #     widget=forms.RadioSelect,
        #     choices=CHOICES_PAY,
        # )


class OrderUpdateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = [
            'paid'
        ]

backend/store/orders/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView, UpdateView, DetailView
import uuid
from django.http import HttpResponseRedirect

from shop.models import ClothingCategories
from .models import OrderItem, Order
from .forms import OrderCreateForm, OrderUpdateForm
from cart.cart import Cart
from yookassa import Configuration, Payment

# Configuration.account_id = '232354'    #OLD
Configuration.account_id = '272258'
# Configuration.secret_key = 'test_00aCox20214_yPcvdR8-Gc79fpbkgMyh0ZgdVxH5Y1Y'    #OLD
Configuration.secret_key = 'test_SHwUbP0Q5bXVFrJr8WB7K3Qf-qNJLbH7cJjfHaVDufA'


def order_create(request):
    clothing = ClothingCategories.objects.all()
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            try:
                order.authorUser = request.user
            except Exception:
                order.authorUser = None
            order.save()

            current_user = order.authorUser
            if current_user == None:
                current_user = 'Незарегистрирован'
            else:
                current_user = order.authorUser.username
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'],
                                         color=item['product'].colors,      #Берём продукт и обращаемся к полю его цвета
                                         size=item['size'],
                                         user=current_user
                                         )

            total = cart.get_total_price()
            print(f'http://127.0.0.1:8000/orders/order_detail/{order.id}/')
            payment = Payment.create({
                "amount": {
                    "value": f'{total}',
                    "currency": "RUB",
                },
                "confirmation": {
                    "type": "redirect",
                    "return_url": "http://127.0.0.1:8000/"
                },
                "capture": True,
                "description": f'http://127.0.0.1:8000/orders/order_detail/{order.id}/'
            }, uuid.uuid4())
            # очистить корзину
            print(payment)
            cart.clear()
            return HttpResponseRedirect(payment.confirmation.confirmation_url)
        else:
            zero = 0
            return render(request, 'categories.html', {'zero': zero})
    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/create.html',
                  {'cart': cart, 'form': form, 'clothing': clothing}
                  )


class OrderList(PermissionRequiredMixin, ListView):
    permission_required = (
        'orders.order_item.view_order_item',
    )
    model = OrderItem
    context_object_name = 'orders'
    template_name = 'orders/order_list.html'
    queryset = OrderItem.objects.all()


class OrderUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = (
        'orders.order_item.change_order',
    )
    template_name = 'orders/update.html'
    form_class = OrderUpdateForm

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Order.objects.get(pk=id)


class OrderDetail(PermissionRequiredMixin, DetailView):
    permission_required = (
        'orders.order_item.view_order',
    )
    template_name = 'orders/order_detail.html'
    context_object_name = 'order'
    queryset = Order.objects.all()

    def all_items_order(self):
        current_order = self.get_object()
        items = OrderItem.objects.filter(order=current_order.id)
        return items

backend/store/templates/orders/create.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}
    <body>
        {% block content %}
        <div class="row align-items-center" style="background-color: #9DA89C; margin-bottom: 2rem; height: 4rem; z-index: 1030; position: relative; margin-left: 0; margin-right: 0;">
            <nav class="navbar navbar-expand-lg" style="background-color: #9DA89C;">
                <div class="container" style="padding-right: 0;">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSecond" aria-controls="navbarSecond" aria-expanded="false"
                            aria-label="Переключатель навигации" style="margin-left: 0; padding-left: 0; border: 0; color: #FFFFFF; box-shadow: none;">
                        <span>
                            Каталог <img src="/static/ico/downmenu_second_nav.png">
                        </span>
                    </button>
                    <div class="navbar-toggler" data-bs-toggle="collapse"
                         style="margin-left: 1rem; border: 0; color: #FFFFFF;">
                         <div class="row" style="justify-content: center;">
                             <div class="col-3">
                                 <a href="/profile/">
                                     <img src="/static/ico/profile_white.png">
                                 </a>
                             </div>
                             <div class="col-3">
                                 <a href="{% url 'favorite' %}">
                                    <img src="/static/ico/favorite_white.png">
                                 </a>
                             </div>
                             <div class="col-3">
                                 <a href="{% url 'cart_detail' %}" style="text-decoration: none; color: #825934; font-weight: bold;">
                                    <img src="/static/ico/cart_white.png">
                                 </a>
                             </div>
                        </div>
                    </div>
                    <div class="collapse navbar-collapse" id="navbarSecond">
                        <ul class="navbar-nav w-100 justify-content-center">
                            {% for cat in clothing %}
                                <li class="nav-item" style="margin-right: 2rem;">
                                    <a class="nav-link active" aria-current="page" href="{% url 'category_clothing' cat.id %}" style="color: snow; padding-left: 10px;">
                                        {{cat.name}}
                                        <img src="/static/ico/downmenu.png">
                                    </a>
                                </li>
                            {% endfor %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="#" style="color: white; padding-left: 10px;">
                                    Капсулы
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="container">
            <h3>Корзина</h3>
            {% for item in cart %}
                {% with product=item.product %}
                    <div class="row">
                        <div class="col">           <!-- for imagine -->
                            <img src="{{MEDIA_URL}}{{product.photo_1.url}}" class="d-block w-100" alt="..."
                                 style="border-radius: 10px; max-width: 100px; min-width: 10vw;">
                        </div>
                        <div class="col">           <!-- for info -->
                            <div class="row">
                                <div class="col">       <!-- for name -->
                                    {{ product.name }}
                                </div>
                                <div class="col">       <!-- for size -->
                                    {{ item.size }}
                                </div>
                                <div class="col">       <!-- for color -->
                                    {{ product.colors }}
                                </div>
                            </div>
                        </div>
                        <div class="col">           <!-- for other -->
                            <div class="row" style="align-items: center; text-align: center;">
                                <div class="col">       <!-- for favorite -->
                                    {% if product.name in request.user.favorite_products.all|join:", " %}
                                        <form action="{% url 'delete_favorite' %}" method="post" style="text-align: right">
                                            {% csrf_token %}
                                            <input type="hidden" name="id_cat" value={{product.id}}>
                                            <button type="submit" class="btn" style="background-color: #fff0; border: #fff0; padding-right:0">
                                                <img src="/static/ico/favorite3.png">
                                            </button>
                                        </form>
                                    {% else %}
                                        <form action="{% url 'add_favorite' %}" method="post" style="text-align: right">
                                            {% csrf_token %}
                                            <input type="hidden" name="id_cat" value={{product.id}}>
                                            <button type="submit" class="btn" style="background-color: #fff0; border: #fff0; padding-right:0">
                                                <img src="/static/ico/favorite.png">
                                            </button>
                                        </form>
                                    {% endif %}
                                </div>
                                <div class="col">       <!-- for delete -->
                                    <a href="{% url 'cart_remove' product.id %}">
                                        <img src="/static/ico/delete.png">
                                    </a>
                                </div>
                                <div class="col">       <!-- for quantity -->
                                    {{ item.quantity }}
                                </div>
                                <div class="col" style="color: #825934; font-weight: bold;">       <!-- for price -->
                                    {{ item.total_price }}₽
                                </div>
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
            <h3>Оформление заказа</h3>
             <form method="post" class="order-form" style="margin-bottom: 5rem;">
                 <div class="row"  style="margin-bottom: 1rem;">
                     <div class="col" style="margin-right: 2rem">
                         <div style="padding-top: 0.375rem; padding-right: 0.75rem; padding-bottom: 0.375rem; font-weight: bold">Адрес</div>
                         <div style="margin-bottom: 1rem">{{ form.country }}</div>
                         <div style="margin-bottom: 1rem">{{ form.city }}</div>
                         <div style="margin-bottom: 1rem">{{ form.postal_code }}</div>
                         <div style="margin-bottom: 1rem">{{ form.address }}</div>
                         <div style="padding-top: 0.375rem; padding-right: 0.75rem; padding-bottom: 0.375rem; font-weight: bold">Покупатель</div>
                         <div style="margin-bottom: 1rem">{{ form.name }}</div>
                         <div style="margin-bottom: 1rem">{{ form.email }}</div>
                         <div style="margin-bottom: 1rem">{{ form.phone }}</div>
                     </div>
                     <div class="col formOrderCreate">
                         <div style="padding-top: 0.375rem; padding-right: 0.75rem; padding-bottom: 0.375rem; font-weight: bold">Выберите способ оплаты</div>
<!--                         <div style="margin-bottom: 1rem">{{ form.type_pay }}</div>-->
                         <div style="margin-bottom: 1rem">
                             {% for type in form.type_pay %}
                             <span class="radio-color">{{ type.tag }}</span>
                                {{ type.choice_label }}<br>
                             {% endfor %}
                         </div>
                     </div>
                     <div class="col">
                         <div style="padding-top: 0.375rem; padding-right: 0.75rem; padding-bottom: 0.375rem; font-weight: bold">Выберите способ доставки</div>
<!--                         <div style="margin-bottom: 1rem">{{ form.delivery }}</div>-->
                         <div style="margin-bottom: 1rem">
                             {% for delivery in form.delivery %}
                             <span class="radio-color">{{ delivery.tag }}</span>
                                {{ delivery.choice_label }}<br>
                             {% endfor %}
                         </div>
                         <button type="submit" class="btn" style="margin-top: 10px;
                                                                         border-radius: 20px;
                                                                                    --bs-btn-color: #FFFFFF;
                                                                                    --bs-btn-bg: #825934;
                                                                                    --bs-btn-border-color: #8b4513;
                                                                                    --bs-btn-hover-color: #fff;
                                                                                    --bs-btn-hover-bg: #b35c1e;
                                                                                    --bs-btn-hover-border-color: #8b4513;
                                                                                    --bs-btn-focus-shadow-rgb: 49,132,253;
                                                                                    --bs-btn-active-color: #fff;
                                                                                    --bs-btn-active-bg: #8b4513;
                                                                                    --bs-btn-active-border-color: #8b4513;
                                                                                    --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
                                                                                    --bs-btn-disabled-color: #fff;
                                                                                    --bs-btn-disabled-bg: #8b4513;
                                                                                    --bs-btn-disabled-border-color: #8b4513;">
                            Оформить заказ
                        </button>
                     </div>
                 </div>
                 {% csrf_token %}
             </form>
        </div>
        {% endblock content %}
    </body>
</html>

backend/store/templates/orders/created.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
    <body>
        {% block content %}
            <div class="container">
                <h1>Спасибо!</h1>
                <p>Оформление заказа прошло успешно. Ваш номер заказа
                <strong>{{ order.id }}</strong>.</p>
            </div>
        {% endblock content%}
    </body>
</html>

backend/store/templates/orders/order_detail.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}
    <body>
        {% block content %}
        <div class="container">
            <table class="table" style="margin-bottom: 5rem">
                <thead>
                    <tr>
                        <th>ФИО</th>
                        <th>Страна</th>
                        <th>Эл.почта</th>
                        <th>Адрес</th>
                        <th>Индекс</th>
                        <th>Город</th>
                        <th>Телефон</th>
                        <th>Пользователь</th>
                        <th>Дата заказа</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ order.name }}</td>
                        <td>{{ order.country }}</th>
                        <td>{{ order.email }}</td>
                        <td>{{ order.address }}</td>
                        <td>{{ order.postal_code }}</td>
                        <td>{{ order.city }}</td>
                        <td>{{ order.phone }}</td>
                        <td>{{ order.authorUser }}</td>
                        <td>{{ order.created | date:"d.m.Y" }}</td>
                    </tr>
                </tbody>
             </table>
             <table class="table">
                <thead>
                    <tr>
                        <th>Заказ</th>
                        <th>Продукт</th>
                        <th>Цена</th>
                        <th>Колличство</th>
                        <th>Цвет</th>
                        <th>Размер</th>
                        <th>Отправка</th>
                    </tr>
                </thead>
                <tbody>
                {% for order in view.all_items_order %}
                    <tr>
                        <td>{{ order.order }}</td>
                        <td>{{ order.product.name }}</td>
                        <td>{{ order.price }}</td>
                        <td>{{ order.quantity }}</td>
                        <td>{{ order.color }}</td>
                        <td>{{ order.size }}</td>
                        <td><a href="{% url 'orders:order_update' order.id %}">{{ order.order.paid }}</a></td>
                    </tr>
                {% endfor %}
                </tbody>
             </table>
        </div>
        {% endblock content %}
    </body>
</html>

backend/store/templates/orders/order_list.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}
    <body>
        {% block content %}
        <div class="container">
             <table class="table">
                <thead>
                    <tr>
                        <th>Заказ</th>
                        <th>Продукт</th>
                        <th>Цена</th>
                        <th>Колличство</th>
                        <th>Цвет</th>
                        <th>Размер</th>
                        <th>Отправка</th>
                    </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                    <tr>
                        <td>{{ order.order }}</td>
                        <td>{{ order.product.name }}</td>
                        <td>{{ order.price }}</td>
                        <td>{{ order.quantity }}</td>
                        <td>{{ order.color }}</th>
                        <td>{{ order.size }}</td>
                        <td><a href="{% url 'orders:order_update' order.id %}">{{ order.order.paid }}</a></td>
                    </tr>
                {% endfor %}
                </tbody>
             </table>
        </div>
        {% endblock content %}
    </body>
</html>

backend/store/templates/orders/pay.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
    <body>
        {% block content %}
            <div class="container">
                <form method='POST' action='https://demo.paykeeper.ru/create/' >
                    <p>Ваш номер заказа<strong>{{ order.id }}</strong>.</p>
                  Сумма оплаты:
                    <input type='text' name='sum' value="{{ cart.get_total_price }}"/> <br />
                  Введите номер заказа:
                    <input type='text' name='orderid' value='{{ order.id }}'/> <br />
                  Введите название услуги:
                    <input type='text' name='service_name' value='Тестовая оплата'/> <br />
                  <input type='submit' value='Перейти к оплате' />
                </form>
            </div>
        {% endblock content%}
    </body>
</html>

backend/store/templates/orders/update.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}
    <body>
        {% block content %}
        <div class="container">
             <div class="order-info" style="margin-bottom: 2rem;">
                 <h3>Отметка об отправке</h3>
                 <table class="table">
                    <thead>
                        <tr>
                            <th>Номер заказа</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ order.id }}</td>
                        </tr>
                    </tbody>
                 </table>
             </div>
            <h3>Состояние заказа</h3>
             <form method="post" class="order-form" style="margin-bottom: 5rem;">
                 Отправка {{ form.paid }}
                 <button type="submit" class="btn" style="margin-top: 10px;
                                                                 border-radius: 20px;
                                                                            --bs-btn-color: #FFFFFF;
                                                                            --bs-btn-bg: #825934;
                                                                            --bs-btn-border-color: #8b4513;
                                                                            --bs-btn-hover-color: #fff;
                                                                            --bs-btn-hover-bg: #b35c1e;
                                                                            --bs-btn-hover-border-color: #8b4513;
                                                                            --bs-btn-focus-shadow-rgb: 49,132,253;
                                                                            --bs-btn-active-color: #fff;
                                                                            --bs-btn-active-bg: #8b4513;
                                                                            --bs-btn-active-border-color: #8b4513;
                                                                            --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
                                                                            --bs-btn-disabled-color: #fff;
                                                                            --bs-btn-disabled-bg: #8b4513;
                                                                            --bs-btn-disabled-border-color: #8b4513;">
                    OK
                 </button>
                 {% csrf_token %}
             </form>
        </div>
        {% endblock content %}
    </body>
</html>