backend/store/api/urls.py
from django.urls import path
from .views import ProductAPIVew, CollectionAPIVew, CategoryProductAPIVew, ClothingCategoriesAPIVew, \
    ClientCategoryAPIVew, StockAPIVew, ProductDetailAPIVew, CreateClientCategoryAPIVew, CreateCollectionAPIVew, \
    CreateClothingCategoriesAPIVew, CreateProductAPIVew, CreateStockAPIVew, CreateCategoryProductAPIVew


urlpatterns =[
    path('products/', ProductAPIVew.as_view()),
    path('collection/', CollectionAPIVew.as_view()),
    path('category_product/', CategoryProductAPIVew.as_view()),
    path('clothing_categories/', ClothingCategoriesAPIVew.as_view()),
    path('client_category/', ClientCategoryAPIVew.as_view()),
    path('stock/', StockAPIVew.as_view()),
    path('products/<int:pk>/', ProductDetailAPIVew.as_view()),
    #API для добавления
    path('add_client_category', CreateClientCategoryAPIVew.as_view()),
    path('add_collection', CreateCollectionAPIVew.as_view()),
    path('add_clothing_categories', CreateClothingCategoriesAPIVew.as_view()),
    path('add_product', CreateProductAPIVew.as_view()),
    path('add_stock', CreateStockAPIVew.as_view()),
    path('add_category_product', CreateCategoryProductAPIVew.as_view()),
]

backend/store/cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove

urlpatterns =[
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

backend/store/orders/urls.py
from django.urls import path
from .views import order_create, OrderList, OrderUpdate, OrderDetail


app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('order_list/', OrderList.as_view(), name='order_list'),
    path('order_update/<int:pk>/', OrderUpdate.as_view(), name='order_update'),
    path('order_detail/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
]

backend/store/store/urls.py
from django.contrib import admin
from django.urls import path, include
#импорты для настройки картинки
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('sign/', include('sign.urls')),
    path('profile/', include('protect.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
] #+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # без этой настройки не будет отображения картинки

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/store/cart/forms.py
from django import forms
from shop.models import Product, Size


class CartAddProductForm(forms.Form):

    PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 2)]

    sizes = Size.objects.all()
    size_list = []
    for size in sizes:
        size_list.append(size.size)
    PRODUCT_SIZE_CHOICES = [(str(s), str(s)) for s in size_list]

    quantity = forms.TypedChoiceField(label='Колличество', choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    size = forms.TypedChoiceField(label='Цвет', choices=PRODUCT_SIZE_CHOICES, coerce=str)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

backend/store/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product, ClothingCategories
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 size=cd['size'],
                 update_quantity=cd['update']
                 )
    return redirect('cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart_detail')


def cart_detail(request):
    cart = Cart(request)
    clothing = ClothingCategories.objects.all()
    return render(request, 'cart/detail_new.html', {'cart': cart, 'clothing': clothing})

backend/store/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div style="font-size: larger; background-color: #9DA89C; margin-bottom: 1rem">
        <ul class="nav justify-content-center">
            {% for cat in clothing %}
                <li class="nav-item" style="z-index:2">
                   <a class="nav-link active" aria-current="page" href="{% url 'category_clothing' cat.id %}"
                      style="color: white">
                       {{cat.name}}
                       <img src="/static/ico/downmenu.png">
                   </a>
                </li>
            {% endfor %}
            <li class="nav-item" style="z-index:2">
                <a class="nav-link active" aria-current="page" href="#" style="color: white">
                    Капсулы
                </a>
            </li>
        </ul>
    </div>
    <div class="container">
        <ul class="nav justify-content-start" style="margin-bottom: 2rem">
            <li class="nav-item" style="z-index:2">
               <a class="nav-link active" aria-current="page" href="#" style="padding-left: 0; color: #000000; text-decoration: underline;">
                   Условия доставки
               </a>
            </li>
            <li class="nav-item" style="z-index:2">
               <a class="nav-link active" aria-current="page" href="#" style="color: #000000; text-decoration: underline;">
                   Оплата товара
               </a>
            </li>
            <li class="nav-item" style="z-index:2">
               <a class="nav-link active" aria-current="page" href="#" style="color: #000000; text-decoration: underline;">
                   Возврат товара
               </a>
            </li>
        </ul>
        <h3>Корзина</h3>
        <table class="table">
            <thead>
            <tr>
                <th></th>
                <th>Наименование</th>
                <th>Размер</th>
                <th>Цвет</th>
                <th>Цена</th>
                <th>Кол-во</th>
                <th>Сумма</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td style="width: 10%">
                            <img src="{{MEDIA_URL}}{{product.photo_1.url}}"
                                 class="d-block w-100" alt="..." style="border-radius: 10px">
                        </td>
                        <td>{{ product.name }}</td>
                        <td>{{ item.size }}</td>
                        <td>{{ product.colors }}</td>
                        <td class="num" style="color: #825934; font-weight: bold"> {{ item.price }} ₽</td>
                        <td>{{ item.quantity }}</td>
                        <td class="num" style="color: #825934; font-weight: bold"> {{ item.total_price }} ₽</td>
                        <td>
                            <a href="#">
                                <img src="/static/ico/favorite2.png">
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'cart_remove' product.id %}">
                                <img src="/static/ico/delete.png">
                            </a>
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <!--
            <tr class="total">
                <td>Итого</td>
                <td colspan="4"></td>
                <td class="num">₽ {{ cart.get_total_price }}</td>
            </tr>
            -->
            </tbody>
        </table>
        <div class="row justify-content-end">
            <div class="col-4" style="text-align-last: right;">
                <div class="row">
                    <div class="col" style="font-size: x-large">
                        Итого:
                    </div>
                    <div class="col" style="color: #825934; font-size: x-large; font-weight: bold">
                        {{ cart.get_total_price }} ₽
                    </div>
                </div>
            </div>
        </div>
        <p class="text-right">
            <!--
            <a href="{% url 'categories_global' %}" class="button light">Продолжить просмотр товаров</a>
            -->
            <a href="{% url 'orders:order_create' %}" class="btn" style="margin-top: 10px;
                                                                         border-radius: 20px;
                                                                                    --bs-btn-color: #FFFFFF;
                                                                                    --bs-btn-bg: #825934;
                                                                                    --bs-btn-border-color: #8b4513;
                                                                                    --bs-btn-hover-color: #fff;
                                                                                    --bs-btn-hover-bg: #b35c1e;
                                                                                    --bs-btn-hover-border-color: #8b4513;
                                                                                    --bs-btn-focus-shadow-rgb: 49,132,253;
                                                                                    --bs-btn-active-color: #fff;
                                                                                    --bs-btn-active-bg: #8b4513;
                                                                                    --bs-btn-active-border-color: #8b4513;
                                                                                    --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
                                                                                    --bs-btn-disabled-color: #fff;
                                                                                    --bs-btn-disabled-bg: #8b4513;
                                                                                    --bs-btn-disabled-border-color: #8b4513;">Перейти к оформлению</a>
        </p>
    </div>
{% endblock %}

backend/store/templates/cart/detail_new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row align-items-center" style="background-color: #9DA89C; margin-bottom: 2rem; height: 4rem; z-index: 1030; position: relative; margin-left: 0; margin-right: 0;">
        <nav class="navbar navbar-expand-lg" style="background-color: #9DA89C;">
            <div class="container" style="padding-right: 0;">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSecond" aria-controls="navbarSecond" aria-expanded="false"
                        aria-label="Переключатель навигации" style="margin-left: 0; padding-left: 0; border: 0; color: #FFFFFF; box-shadow: none;">
                    <span>
                        Каталог <img src="/static/ico/downmenu_second_nav.png">
                    </span>
                </button>
                <div class="navbar-toggler" data-bs-toggle="collapse"
                     style="margin-left: 1rem; border: 0; color: #FFFFFF;">
                     <div class="row" style="justify-content: center;">
                         <div class="col-3">
                             <a href="/profile/">
                                 <img src="/static/ico/profile_white.png">
                             </a>
                         </div>
                         <div class="col-3">
                             <a href="{% url 'favorite' %}">
                                <img src="/static/ico/favorite_white.png">
                             </a>
                         </div>
                         <div class="col-3">
                             <a href="{% url 'cart_detail' %}" style="text-decoration: none; color: #825934; font-weight: bold;">
                                <img src="/static/ico/cart_white.png">
                             </a>
                         </div>
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="navbarSecond">
                    <ul class="navbar-nav w-100 justify-content-center">
                        {% for cat in clothing %}
                            <li class="nav-item" style="margin-right: 2rem;">
                                <a class="nav-link active" aria-current="page" href="{% url 'category_clothing' cat.id %}" style="color: snow; padding-left: 10px;">
                                    {{cat.name}}
                                    <img src="/static/ico/downmenu.png">
                                </a>
                            </li>
                        {% endfor %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#" style="color: white; padding-left: 10px;">
                                Капсулы
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        </div>
    <div class="container">
<!--        <ul class="nav justify-content-start" style="margin-bottom: 2rem">-->
<!--            <li class="nav-item" style="z-index:2">-->
<!--               <a class="nav-link active" aria-current="page" href="#" style="padding-left: 0; color: #000000; text-decoration: underline;">-->
<!--                   Условия доставки-->
<!--               </a>-->
<!--            </li>-->
<!--            <li class="nav-item" style="z-index:2">-->
<!--               <a class="nav-link active" aria-current="page" href="#" style="color: #000000; text-decoration: underline;">-->
<!--                   Оплата товара-->
<!--               </a>-->
<!--            </li>-->
<!--            <li class="nav-item" style="z-index:2">-->
<!--               <a class="nav-link active" aria-current="page" href="#" style="color: #000000; text-decoration: underline;">-->
<!--                   Возврат товара-->
<!--               </a>-->
<!--            </li>-->
<!--        </ul>-->
        <h3>Корзина</h3>
        {% for item in cart %}
                {% with product=item.product %}
        <div class="row">
            <div class="col">         <!-- Для фото -->
                <img src="{{MEDIA_URL}}{{product.photo_1.url}}" class="d-block w-100" alt="..."
                     style="border-radius: 10px; max-width: 100px; min-width: 10vw;">
            </div>
            <div class="col">         <!-- для имени размера и цвета -->
                <div class="row">
                    <div class="col">     <!-- имя -->
                        {{ product.name }}
                    </div>
                    <div class="col">     <!-- размер -->
                        {{ item.size }}
                    </div>
                    <div class="col">     <!-- цвета -->
                        {{ product.colors }}
                    </div>
                </div>
            </div>
            <div class="col">         <!-- для избранного удаления колличества и цены -->
                <div class="row">
                    <div class="col">     <!-- избранное -->
                        <a href="#">
                            <img src="/static/ico/favorite2.png">
                        </a>
                    </div>
                    <div class="col">     <!-- удаление -->
                        <a href="{% url 'cart_remove' product.id %}">
                            <img src="/static/ico/delete.png">
                        </a>
                    </div>
                    <div class="col">     <!-- колличество -->
                        {{ item.quantity }}
                    </div>
                    <div class="col">     <!-- цена -->
                        {{ item.total_price }} ₽
                    </div>
                </div>
            </div>
        </div>
             {% endwith %}
        {% endfor %}
        <div class="row justify-content-end">
            <div class="col-5" style="text-align-last: right;">
                <div class="row">
                    <div class="col" style="font-size: x-large">
                        Итого:
                    </div>
                    <div class="col" style="color: #825934; font-size: x-large; font-weight: bold">
                        {{ cart.get_total_price }} ₽
                    </div>
                </div>
            </div>
        </div>
        <p class="text-right" style="text-align: center;">
            <!--
            <a href="{% url 'categories_global' %}" class="button light">Продолжить просмотр товаров</a>
            -->
            <a href="{% url 'orders:order_create' %}" class="btn" style="margin-top: 10px;
                                                                         margin-bottom: 5rem;
                                                                         border-radius: 20px;
                                                                                    --bs-btn-color: #FFFFFF;
                                                                                    --bs-btn-bg: #825934;
                                                                                    --bs-btn-border-color: #8b4513;
                                                                                    --bs-btn-hover-color: #fff;
                                                                                    --bs-btn-hover-bg: #b35c1e;
                                                                                    --bs-btn-hover-border-color: #8b4513;
                                                                                    --bs-btn-focus-shadow-rgb: 49,132,253;
                                                                                    --bs-btn-active-color: #fff;
                                                                                    --bs-btn-active-bg: #8b4513;
                                                                                    --bs-btn-active-border-color: #8b4513;
                                                                                    --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
                                                                                    --bs-btn-disabled-color: #fff;
                                                                                    --bs-btn-disabled-bg: #8b4513;
                                                                                    --bs-btn-disabled-border-color: #8b4513;">Перейти к оформлению</a>
        </p>
    </div>
{% endblock %}